/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import component.CustomConfirmDialog;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import main.Main;
import static others.BienMacDinh.mauDanhMucDangChon;
import static others.BienMacDinh.mauDen;
import static others.BienMacDinh.mauNenMenu;
import static others.BienMacDinh.mauTrang;
import xuli.ChuyenManHinh;
import xuli.DanhMucBean;

/**
 *
 * @author acer
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() throws SQLException {
        icon();
        this.setTitle("Quản lí mua bán xe máy tại cửa hàng VinaBike.");
        initComponents();
        setLocationRelativeTo(null);

        ChuyenManHinh dieuKhien = new ChuyenManHinh(jpnThaoTac);
        dieuKhien.setManHinhNoiDung(pnlQLSanPham, lblQLSanPham);

        List<DanhMucBean> listDanhMucBean = new ArrayList<>();
        listDanhMucBean.add(new DanhMucBean("SanPham", pnlQLSanPham, lblQLSanPham));
        listDanhMucBean.add(new DanhMucBean("QLBanHang", pnlQLBanHang, lblQLBanHang));
        listDanhMucBean.add(new DanhMucBean("QLHopDong", pnlQLHopDong, lblQLHopDong));
        listDanhMucBean.add(new DanhMucBean("QLKhachHang", pnlQLKhachHang, lblQLKhachHang));
        listDanhMucBean.add(new DanhMucBean("QLHoaDon", pnlQLHoaDon, lblQLHoaDon));
        listDanhMucBean.add(new DanhMucBean("QLNhanVien", pnlQLNhanVien, lblQLNhanVien));

        dieuKhien.setSuKienClickDanhMuc(listDanhMucBean);
    }

    public void icon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo_XeMay.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnGDChinh = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlQLSanPham = new javax.swing.JPanel();
        lblQLSanPham = new javax.swing.JLabel();
        pnlQLBanHang = new javax.swing.JPanel();
        lblQLBanHang = new javax.swing.JLabel();
        pnlQLHopDong = new javax.swing.JPanel();
        lblQLHopDong = new javax.swing.JLabel();
        pnlQLKhachHang = new javax.swing.JPanel();
        lblQLKhachHang = new javax.swing.JLabel();
        pnlQLHoaDon = new javax.swing.JPanel();
        lblQLHoaDon = new javax.swing.JLabel();
        pnlQLNhanVien = new javax.swing.JPanel();
        lblQLNhanVien = new javax.swing.JLabel();
        jpnLogOut = new javax.swing.JPanel();
        lblDangXuat = new javax.swing.JLabel();
        jpnThaoTac = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnGDChinh.setBackground(new java.awt.Color(255, 255, 255));

        jpnMenu.setBackground(new java.awt.Color(194, 228, 255));
        jpnMenu.setPreferredSize(new java.awt.Dimension(221, 730));

        pnlLogo.setBackground(new java.awt.Color(194, 228, 255));

        lblLogo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(204, 51, 0));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_XeMay.png"))); // NOI18N
        lblLogo.setText("VinaBike");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlQLSanPham.setBackground(new java.awt.Color(194, 228, 255));

        lblQLSanPham.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product_32px.png"))); // NOI18N
        lblQLSanPham.setText("Sản phẩm");
        lblQLSanPham.setToolTipText("Sản phẩm");
        lblQLSanPham.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout pnlQLSanPhamLayout = new javax.swing.GroupLayout(pnlQLSanPham);
        pnlQLSanPham.setLayout(pnlQLSanPhamLayout);
        pnlQLSanPhamLayout.setHorizontalGroup(
            pnlQLSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQLSanPhamLayout.setVerticalGroup(
            pnlQLSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlQLBanHang.setBackground(new java.awt.Color(194, 228, 255));

        lblQLBanHang.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart_32px.png"))); // NOI18N
        lblQLBanHang.setText("Quản lí bán hàng");
        lblQLBanHang.setToolTipText("Quản lí bán hàng");
        lblQLBanHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout pnlQLBanHangLayout = new javax.swing.GroupLayout(pnlQLBanHang);
        pnlQLBanHang.setLayout(pnlQLBanHangLayout);
        pnlQLBanHangLayout.setHorizontalGroup(
            pnlQLBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQLBanHangLayout.setVerticalGroup(
            pnlQLBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlQLHopDong.setBackground(new java.awt.Color(194, 228, 255));

        lblQLHopDong.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contract_32px.png"))); // NOI18N
        lblQLHopDong.setText("Quản lí hợp đồng");
        lblQLHopDong.setToolTipText("Quản lí hợp đồng");
        lblQLHopDong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout pnlQLHopDongLayout = new javax.swing.GroupLayout(pnlQLHopDong);
        pnlQLHopDong.setLayout(pnlQLHopDongLayout);
        pnlQLHopDongLayout.setHorizontalGroup(
            pnlQLHopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLHopDongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQLHopDongLayout.setVerticalGroup(
            pnlQLHopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLHopDongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlQLKhachHang.setBackground(new java.awt.Color(194, 228, 255));

        lblQLKhachHang.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer_32px.png"))); // NOI18N
        lblQLKhachHang.setText("Quản lí khách hàng");
        lblQLKhachHang.setToolTipText("Quản lí khách hàng");
        lblQLKhachHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout pnlQLKhachHangLayout = new javax.swing.GroupLayout(pnlQLKhachHang);
        pnlQLKhachHang.setLayout(pnlQLKhachHangLayout);
        pnlQLKhachHangLayout.setHorizontalGroup(
            pnlQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQLKhachHangLayout.setVerticalGroup(
            pnlQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlQLHoaDon.setBackground(new java.awt.Color(194, 228, 255));

        lblQLHoaDon.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payment_32px.png"))); // NOI18N
        lblQLHoaDon.setText("Quản lí hóa đơn");
        lblQLHoaDon.setToolTipText("Quản lí hóa đơn");
        lblQLHoaDon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout pnlQLHoaDonLayout = new javax.swing.GroupLayout(pnlQLHoaDon);
        pnlQLHoaDon.setLayout(pnlQLHoaDonLayout);
        pnlQLHoaDonLayout.setHorizontalGroup(
            pnlQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQLHoaDonLayout.setVerticalGroup(
            pnlQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlQLNhanVien.setBackground(new java.awt.Color(194, 228, 255));

        lblQLNhanVien.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee_32px.png"))); // NOI18N
        lblQLNhanVien.setText("Quản lí nhân viên");
        lblQLNhanVien.setToolTipText("Quản lí hóa đơn");
        lblQLNhanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout pnlQLNhanVienLayout = new javax.swing.GroupLayout(pnlQLNhanVien);
        pnlQLNhanVien.setLayout(pnlQLNhanVienLayout);
        pnlQLNhanVienLayout.setHorizontalGroup(
            pnlQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQLNhanVienLayout.setVerticalGroup(
            pnlQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnLogOut.setBackground(new java.awt.Color(194, 228, 255));

        lblDangXuat.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_32px.png"))); // NOI18N
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnLogOutLayout = new javax.swing.GroupLayout(jpnLogOut);
        jpnLogOut.setLayout(jpnLogOutLayout);
        jpnLogOutLayout.setHorizontalGroup(
            jpnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnLogOutLayout.setVerticalGroup(
            jpnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLogOutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQLBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQLHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlQLBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlQLHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlQLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jpnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnThaoTac.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jpnThaoTacLayout = new javax.swing.GroupLayout(jpnThaoTac);
        jpnThaoTac.setLayout(jpnThaoTacLayout);
        jpnThaoTacLayout.setHorizontalGroup(
            jpnThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jpnThaoTacLayout.setVerticalGroup(
            jpnThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnGDChinhLayout = new javax.swing.GroupLayout(jpnGDChinh);
        jpnGDChinh.setLayout(jpnGDChinhLayout);
        jpnGDChinhLayout.setHorizontalGroup(
            jpnGDChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnGDChinhLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnThaoTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnGDChinhLayout.setVerticalGroup(
            jpnGDChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThaoTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnGDChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnGDChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseEntered
        jpnLogOut.setBackground(mauDanhMucDangChon);
        lblDangXuat.setBackground(mauDanhMucDangChon);
        lblDangXuat.setForeground(mauTrang);
    }//GEN-LAST:event_lblDangXuatMouseEntered

    private void lblDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseExited
        jpnLogOut.setBackground(mauNenMenu);
        lblDangXuat.setBackground(mauNenMenu);
        lblDangXuat.setForeground(mauDen);
    }//GEN-LAST:event_lblDangXuatMouseExited

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
       CustomConfirmDialog canhBaoDangXuat = new CustomConfirmDialog(this);
        canhBaoDangXuat.showMessage("Cảnh báo đăng xuất?", "Đăng xuất sẽ trở về giao diện đăng nhập\nKiểm tra cần thận trước khi đăng xuất.");
        if (canhBaoDangXuat.getMessageType() == CustomConfirmDialog.MessageType.OK) {
            GDDangNhap gdDangNhap = new GDDangNhap();
            gdDangNhap.setVisible(true);
            Main.gdChinh.setVisible(false);
        } else return;
    }//GEN-LAST:event_lblDangXuatMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpnGDChinh;
    private javax.swing.JPanel jpnLogOut;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnThaoTac;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblQLBanHang;
    private javax.swing.JLabel lblQLHoaDon;
    private javax.swing.JLabel lblQLHopDong;
    private javax.swing.JLabel lblQLKhachHang;
    public static javax.swing.JLabel lblQLNhanVien;
    private javax.swing.JLabel lblQLSanPham;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlQLBanHang;
    private javax.swing.JPanel pnlQLHoaDon;
    private javax.swing.JPanel pnlQLHopDong;
    private javax.swing.JPanel pnlQLKhachHang;
    private javax.swing.JPanel pnlQLNhanVien;
    private javax.swing.JPanel pnlQLSanPham;
    // End of variables declaration//GEN-END:variables

    
}
