/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import component.CustomMessageDialog;
import dao.HopDongDAO;
import dao.KhachHangDAO;
import dao.LoaiSanPhamDAO;
import dao.NhanVienDAO;
import dao.SanPhamDAO;
import entity.HopDong;
import entity.KhachHang;
import entity.LoaiXe;
import entity.NhanVien;
import entity.Xe;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author acer
 */
public class QLBanHang_GUI extends javax.swing.JPanel implements MouseListener {
    
    private LoaiSanPhamDAO loaiSP_DAO;
    private SanPhamDAO sanPham_DAO;
    private KhachHangDAO khachHang_DAO;
    private HopDongDAO hopDong_DAO;
    private NhanVienDAO nhanVien_DAO;
    private GDDangNhap gdDangNhap;
    public HopDong hopDong;
    private DecimalFormat df;
    private double soTienPhaiTT = 0;
    private double soTienDaTT = 0;
    private double soTienConLai = 0;
    private double moiLanGop = 0;
    private String soLanTT;

    /**
     * Creates new form jpnQLBanHang
     */
    public QLBanHang_GUI() throws SQLException {
        initComponents();
        
        gdDangNhap = new GDDangNhap();
        lblTenNhanVien.setText(GDDangNhap.tenNV);
        lblChucVu.setText(GDDangNhap.chucVuNV);
        
        loadDataTuCSDLLenUI();
        hopDong_DAO = new HopDongDAO();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        grGioiTinh = new javax.swing.ButtonGroup();
        grThanhToan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblHoTenKH = new javax.swing.JLabel();
        lblSDTKH = new javax.swing.JLabel();
        lblDiaChiKH = new javax.swing.JLabel();
        txtHoTenKH = new javax.swing.JTextField();
        txtSDTKH = new javax.swing.JTextField();
        txtDiaChiKH = new javax.swing.JTextField();
        lblGioiTinhKH = new javax.swing.JLabel();
        radNu = new javax.swing.JRadioButton();
        radNam = new javax.swing.JRadioButton();
        lblSoCCCD = new javax.swing.JLabel();
        txtSoCCCD = new javax.swing.JTextField();
        lblMaKH = new javax.swing.JLabel();
        cbxMaKhachHang = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        lblMaXe = new javax.swing.JLabel();
        lblTenXe = new javax.swing.JLabel();
        lblMauXe = new javax.swing.JLabel();
        lblNXS = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        txtMauXe = new javax.swing.JTextField();
        txtNSX = new javax.swing.JTextField();
        lblLoaiXe = new javax.swing.JLabel();
        cbxLoaiXe = new javax.swing.JComboBox<>();
        lblSoKhung = new javax.swing.JLabel();
        lblPhanKhoi = new javax.swing.JLabel();
        lblGiaXe = new javax.swing.JLabel();
        txtSoKhung = new javax.swing.JTextField();
        txtPhanKhoi = new javax.swing.JTextField();
        txtGiaXe = new javax.swing.JTextField();
        lblHangXe = new javax.swing.JLabel();
        txtHangXe = new javax.swing.JTextField();
        lblThoiHanBH = new javax.swing.JLabel();
        txtThoiHanBH = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        cbxMaXe = new javax.swing.JComboBox<>();
        lblSoLuong = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaHopDong = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        radTraThang = new javax.swing.JRadioButton();
        radTraGop = new javax.swing.JRadioButton();
        lblTraTruoc = new javax.swing.JLabel();
        txtTraTruoc = new javax.swing.JTextField();
        lblSoLanGop = new javax.swing.JLabel();
        cbxSoLanGop = new javax.swing.JComboBox<>();
        lblMoiLanGop = new javax.swing.JLabel();
        txtMoiLanGop = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoTienPhaiTT = new javax.swing.JTextField();
        lblSoTienPhaiTT = new javax.swing.JLabel();
        lblTienConLai = new javax.swing.JLabel();
        txtTienConLai = new javax.swing.JTextField();
        lblSoLuongMua = new javax.swing.JLabel();
        txtSoLuongMua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnLapHopDong = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(961, 730));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(961, 730));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(961, 70));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÍ BÁN HÀNG");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee_32px.png"))); // NOI18N

        lblTenNhanVien.setText("Tên nhân viên");

        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu.setText("Chức vụ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTenNhanVien)
                    .addComponent(lblChucVu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTenNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChucVu)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(961, 680));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN KHÁCH HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N
        jPanel4.setName(""); // NOI18N

        lblHoTenKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblHoTenKH.setText("Họ tên:");

        lblSDTKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblSDTKH.setText("Số điện thoại:");

        lblDiaChiKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblDiaChiKH.setText("Địa chỉ:");

        txtHoTenKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        txtSDTKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        txtDiaChiKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        lblGioiTinhKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblGioiTinhKH.setText("Giới tính:");

        grGioiTinh.add(radNu);
        radNu.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        radNu.setText("Nữ");

        grGioiTinh.add(radNam);
        radNam.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        radNam.setSelected(true);
        radNam.setText("Nam");

        lblSoCCCD.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblSoCCCD.setText("Số CCCD:");

        txtSoCCCD.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        lblMaKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblMaKH.setText("Mã khách hàng:");

        cbxMaKhachHang.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        cbxMaKhachHang.setToolTipText("Chọn mã khách hàng");
        cbxMaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDiaChiKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSDTKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbxMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHoTenKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGioiTinhKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radNu))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtSDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSoCCCD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoCCCD))
                    .addComponent(txtDiaChiKH))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaKH)
                    .addComponent(cbxMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGioiTinhKH)
                    .addComponent(radNam)
                    .addComponent(radNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoCCCD)
                    .addComponent(txtSoCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHỌN XE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N
        jPanel6.setEnabled(false);

        lblMaXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblMaXe.setText("Mã xe:");

        lblTenXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblTenXe.setText("Tên xe:");
        lblTenXe.setPreferredSize(new java.awt.Dimension(35, 16));

        lblMauXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblMauXe.setText("Màu xe:");
        lblMauXe.setPreferredSize(new java.awt.Dimension(35, 16));

        lblNXS.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblNXS.setText("Nước sản xuất:");
        lblNXS.setPreferredSize(new java.awt.Dimension(35, 16));

        txtTenXe.setEditable(false);
        txtTenXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        txtMauXe.setEditable(false);
        txtMauXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        txtNSX.setEditable(false);
        txtNSX.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        lblLoaiXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblLoaiXe.setText("Loại xe:");

        cbxLoaiXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        lblSoKhung.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblSoKhung.setText("Số khung:");
        lblSoKhung.setPreferredSize(new java.awt.Dimension(35, 16));

        lblPhanKhoi.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblPhanKhoi.setText("Phân khối:");

        lblGiaXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblGiaXe.setText("Giá xe:");

        txtSoKhung.setEditable(false);
        txtSoKhung.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        txtPhanKhoi.setEditable(false);
        txtPhanKhoi.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        txtGiaXe.setEditable(false);
        txtGiaXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        lblHangXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblHangXe.setText("Hãng xe: ");

        txtHangXe.setEditable(false);
        txtHangXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        lblThoiHanBH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblThoiHanBH.setText("Thời hạn bảo hành:");

        txtThoiHanBH.setEditable(false);
        txtThoiHanBH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtThoiHanBH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtThoiHanBH.setText("12 tháng");

        txtSoLuong.setEditable(false);
        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        cbxMaXe.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        cbxMaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaXeActionPerformed(evt);
            }
        });

        lblSoLuong.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblSoLuong.setText("Số lượng: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(lblNXS, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSoKhung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaXe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cbxMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSoKhung))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtTenXe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPhanKhoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGiaXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtPhanKhoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHangXe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtGiaXe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblThoiHanBH, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtThoiHanBH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLoaiXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMaXe)))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPhanKhoi))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPhanKhoi)
                        .addComponent(lblHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNXS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThoiHanBH)
                    .addComponent(txtThoiHanBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Mã hợp đồng:");

        txtMaHopDong.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtMaHopDong.setText("HD0000");

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHỌN HÌNH THỨC MUA HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(895, 220));

        grThanhToan.add(radTraThang);
        radTraThang.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        radTraThang.setText("Mua trả thẳng");
        radTraThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTraThangActionPerformed(evt);
            }
        });

        grThanhToan.add(radTraGop);
        radTraGop.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        radTraGop.setText("Mua trả góp");
        radTraGop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTraGopActionPerformed(evt);
            }
        });

        lblTraTruoc.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblTraTruoc.setText("Nhập số tiền trả trước:");

        txtTraTruoc.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTraTruoc.setForeground(new java.awt.Color(255, 51, 51));
        txtTraTruoc.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtTraTruoc.setEnabled(false);

        lblSoLanGop.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblSoLanGop.setText("Số lần góp:");

        cbxSoLanGop.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        cbxSoLanGop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbxSoLanGop.setEnabled(false);
        cbxSoLanGop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSoLanGopActionPerformed(evt);
            }
        });

        lblMoiLanGop.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblMoiLanGop.setText("Mỗi lần góp:");

        txtMoiLanGop.setEditable(false);
        txtMoiLanGop.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtMoiLanGop.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("<html>\n<body>\nMua từ dưới 3 xe giảm 2%, mua trên 3 xe giảm 5% <br>\nÁp dụng đối với mua trả thẳng\n</body>\n</html>");

        txtSoTienPhaiTT.setEditable(false);
        txtSoTienPhaiTT.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSoTienPhaiTT.setForeground(new java.awt.Color(255, 51, 51));
        txtSoTienPhaiTT.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        lblSoTienPhaiTT.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblSoTienPhaiTT.setText("Số tiền phải thanh toán:");

        lblTienConLai.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblTienConLai.setText("Số tiền còn lại:");

        txtTienConLai.setEditable(false);
        txtTienConLai.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTienConLai.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        lblSoLuongMua.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblSoLuongMua.setText("Số lượng mua:");

        txtSoLuongMua.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*Phần dành cho mua trả góp");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblSoLuongMua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuongMua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(radTraThang)
                                .addGap(18, 18, 18)
                                .addComponent(radTraGop)))
                        .addGap(126, 126, 126)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblTraTruoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTraTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSoLanGop, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(cbxSoLanGop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblSoTienPhaiTT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoTienPhaiTT)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblTienConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTienConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblMoiLanGop, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMoiLanGop, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuongMua, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuongMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radTraThang)
                    .addComponent(radTraGop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTraTruoc)
                    .addComponent(txtTraTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoLanGop, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSoLanGop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTienConLai)
                            .addComponent(lblTienConLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMoiLanGop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMoiLanGop)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoTienPhaiTT)
                            .addComponent(txtSoTienPhaiTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnLapHopDong.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLapHopDong.setForeground(new java.awt.Color(255, 51, 0));
        btnLapHopDong.setText("Lập hợp đồng");
        btnLapHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapHopDongActionPerformed(evt);
            }
        });

        btnNhapLai.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNhapLai.setForeground(new java.awt.Color(255, 51, 0));
        btnNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nhaplai_20px.jpg"))); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLapHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNhapLai)
                .addGap(351, 351, 351))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaHopDong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLapHopDong))
                .addGap(131, 131, 131))
        );

        txtMaHopDong.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLapHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapHopDongActionPerformed
        Object o = evt.getSource();
        CustomMessageDialog batLoiLapHopDong = new CustomMessageDialog(gdDangNhap);
        
        if (o.equals(btnLapHopDong)) {
            if (txtHoTenKH.getText().equals("") || txtSDTKH.getText().equals("") || txtSoCCCD.getText().equals("")
                    || txtDiaChiKH.getText().equals("")) {
                batLoiLapHopDong.showMessage("Thông tin khách hàng", "Vui lòng nhập đầy đủ thông tin khách hàng!");
            } else if (cbxMaXe.getSelectedItem().equals("")) {
                batLoiLapHopDong.showMessage("Cảnh báo chưa chọn xe", "Có vẻ bạn chưa chọn xe, vui lòng chọn xe bạn nhé^^");
                cbxMaXe.requestFocus();
            } else if (txtSoLuongMua.getText().equals("")) {
                batLoiLapHopDong.showMessage("Cảnh báo chưa chọn số lượng mua", "Có vẻ bạn chưa chọn số lượng mua,\n vui lòng chọn số lượng mua bạn nhé^^");
                txtSoLuongMua.requestFocus();
            } else if (txtMaHopDong.getText().equals("")) {
                batLoiLapHopDong.showMessage("Điền mã hợp đồng", "Vui lòng điền mã hợp đồng");
                txtMaHopDong.requestFocus();
            } else if (!(radTraThang.isSelected() || radTraGop.isSelected())) {
                batLoiLapHopDong.showMessage("Hình thức mua hàng", "Vui lòng chọn hình thức mua hàng");
//            } else if (radTraGop.isSelected()) {
//                if (txtTraTruoc.getText().equals("")) {
//                    batLoiLapHopDong.showMessage("Nhập số tiền trả trước", "Vui lòng nhập số tiền trả trước");
//                }
            } else if (validDataLapHopDong()) {
                if (cbxMaKhachHang.getSelectedItem().equals("")) {
                    try {
                        String hoTenKH = txtHoTenKH.getText();
                        String soDT = txtSDTKH.getText();
                        String soCCCD = txtSoCCCD.getText();
                        String diaChi = txtDiaChiKH.getText();
                        boolean gioiTinh = radNu.isSelected();
                        
                        KhachHang kh = new KhachHang(0, hoTenKH, soDT, diaChi, soCCCD, gioiTinh);
                        khachHang_DAO.themKhachHang(kh);
                        int maCuoi = new KhachHangDAO().getLastMaKH();
                        KhachHang kh1 = new KhachHang(maCuoi);
                        
                        String maHopDong = txtMaHopDong.getText();
                        String thoiHanBaoHanh = txtThoiHanBH.getText();
                        LocalDateTime ngayLap = LocalDateTime.now();
//                String ngayLapFormat = getDate(ngayLap.toString());
                        NhanVien nv = new NhanVien(GDDangNhap.maNV);
                        String maXe = (String) cbxMaXe.getSelectedItem();
                        Xe xe = new Xe(maXe);
                        
                        HopDong hopDong = new HopDong(maHopDong, ngayLap, thoiHanBaoHanh, soTienPhaiTT, soTienDaTT, soLanTT, kh1, nv, xe);
                        
                        try {
                            if (hopDong_DAO.getHopDongByMaHopDong(maHopDong) != null && !hopDong_DAO.getHopDongByMaHopDong(maHopDong).isEmpty()) {
                                batLoiLapHopDong.showMessage("Cảnh báo trùng mã hợp đồng", String.format("Có vẻ mã hợp đồng %s đã tồn tại, \n vui lòng nhập mã khác.", maHopDong));
                                
                            } else {
                                hopDong_DAO.lapHopDong(hopDong);
                                capNhatSoLuongXe();
                                batLoiLapHopDong.showMessage("Lập hợp đồng thành công", String.format("Hợp đồng có mã %s vừa tạo thành công, \nvui lòng vào mục Quản lý hợp đồng để kiểm tra.", maHopDong));
                                nhapLai();
                            }
                            
                        } catch (SQLException ex) {
                            ex.printStackTrace();
                            
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                } else {
                    try {
                        int maKH = Integer.parseInt((String) cbxMaKhachHang.getSelectedItem());
                        KhachHang kh = new KhachHang(maKH);
                        
                        String maHopDong = txtMaHopDong.getText();
                        String thoiHanBaoHanh = txtThoiHanBH.getText();
                        LocalDateTime ngayLap = LocalDateTime.now();
//                String ngayLapFormat = getDate(ngayLap.toString());
                        NhanVien nv = new NhanVien(GDDangNhap.maNV);
                        String maXe = (String) cbxMaXe.getSelectedItem();
                        Xe xe = new Xe(maXe);
                        
                        HopDong hopDong = new HopDong(maHopDong, ngayLap, thoiHanBaoHanh, soTienPhaiTT, soTienDaTT, soLanTT, kh, nv, xe);
                        
                        if (hopDong_DAO.getHopDongByMaHopDong(maHopDong) != null && !hopDong_DAO.getHopDongByMaHopDong(maHopDong).isEmpty()) {
                            batLoiLapHopDong.showMessage("Cảnh báo trùng mã hợp đồng", String.format("Có vẻ mã hợp đồng %s đã tồn tại, \n vui lòng nhập mã khác.", maHopDong));
                            
                        } else {
                            hopDong_DAO.lapHopDong(hopDong);
                            capNhatSoLuongXe();
                            batLoiLapHopDong.showMessage("Lập hợp đồng thành công", String.format("Hợp đồng có mã %s vừa tạo thành công, \nvui lòng vào mục Quản lý hợp đồng để kiểm tra.", maHopDong));
                            nhapLai();
                        }
                        
                    } catch (SQLException ex) {
                        batLoiLapHopDong.showMessage("Lập hợp đồng thất bại", "Chúc bạn một ngày tốt lành");
                    }
                }
                
            }
        }
    }//GEN-LAST:event_btnLapHopDongActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        Object o = evt.getSource();
        if (o.equals(btnNhapLai)) {
            nhapLai();
        }
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void cbxMaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaKhachHangActionPerformed
        String maKH = (String) cbxMaKhachHang.getSelectedItem();
        if (maKH == "")
            xoaTrangTTKhachHang();
        else {
            try {
                for (KhachHang kh : khachHang_DAO.getKhachHangByMaKH(maKH)) {
                    txtHoTenKH.setText(kh.getHoTenKH());
                    txtSDTKH.setText(kh.getSoDT());
                    txtSoCCCD.setText(kh.getSoCCCD());
                    txtDiaChiKH.setText(kh.getDiaChi());
                    if (kh.isGioiTinh()) {
                        radNu.setSelected(true);
                    } else {
                        radNam.setSelected(true);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(QLBanHang_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbxMaKhachHangActionPerformed

    private void cbxMaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaXeActionPerformed
        String maXe = (String) cbxMaXe.getSelectedItem();
        try {
            for (Xe xe : sanPham_DAO.getSanPhamXeByMaXe(maXe)) {
                txtTenXe.setText(xe.getTenXe());
                txtMauXe.setText(xe.getMauXe());
                txtNSX.setText(xe.getNuocSanXuat());
                txtHangXe.setText(xe.getHangXe());
                txtGiaXe.setText(df.format(xe.getGiaXe()) + "");
                txtSoKhung.setText(xe.getSoKhung());
                txtPhanKhoi.setText(xe.getPhanKhoi());
                txtSoLuong.setText(xe.getSoLuong() + "");
                cbxLoaiXe.setSelectedItem(xe.getLoaiXe().getMaLoaiXe());
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLBanHang_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxMaXeActionPerformed

    private void cbxSoLanGopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSoLanGopActionPerformed
        CustomMessageDialog thongBaoNhapLieu = new CustomMessageDialog(gdDangNhap);
        if (txtTraTruoc.getText().equals("")) {
            thongBaoNhapLieu.showMessage("Thông báo nhập thiếu", "Vui lòng nhập số tiền trả trước");
            txtTraTruoc.requestFocus();
            cbxSoLanGop.setSelectedItem("");
        } else if (cbxSoLanGop.getSelectedItem().equals("")) {
            thongBaoNhapLieu.showMessage("Chọn số lần góp", "Vui lòng chọn số lần góp.");
        }else { 
            soTienDaTT = Double.parseDouble(txtTraTruoc.getText());
            if (soTienDaTT < soTienPhaiTT) {
                soTienConLai = soTienPhaiTT - soTienDaTT;
                
                if (cbxSoLanGop.getSelectedItem().equals("2")) {
                    moiLanGop = soTienConLai / 2;
                    soLanTT = "2";
                } else if (cbxSoLanGop.getSelectedItem().equals("3")) {
                    moiLanGop = soTienConLai / 3;
                    soLanTT = "3";
                }
                df = new DecimalFormat();
                txtTienConLai.setText(df.format(soTienConLai) + "");
                txtMoiLanGop.setText(df.format(moiLanGop) + "");
                
            } else if (soTienDaTT > soTienPhaiTT) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập lại số tiền trả trước, số tiền trả trước phải nhỏ hơn số tiền phải thanh toán.");
                txtTraTruoc.selectAll();
                txtTraTruoc.requestFocus();
                txtTienConLai.setText("");
                txtMoiLanGop.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn hình thức mua trả thẳng");
                txtTienConLai.setText("0");
                txtMoiLanGop.setText("0");
                
            }
        }
    }//GEN-LAST:event_cbxSoLanGopActionPerformed

    private void radTraGopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTraGopActionPerformed
        Object o = evt.getSource();
        if (o.equals(radTraGop)) {
            
            if (txtSoLuongMua.getText().equals("") || cbxMaXe.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn xe và số lượng mua", "Cần chọn xe", JOptionPane.WARNING_MESSAGE);
                grThanhToan.clearSelection();
            } else if (validDataLapHopDong()) {
                txtTraTruoc.setEnabled(true);
                cbxSoLanGop.setEnabled(true);
                
                String maXe = (String) cbxMaXe.getSelectedItem();
                int soLuongMua = Integer.parseInt(txtSoLuongMua.getText());
                double giaXe = Double.parseDouble(txtGiaXe.getText());
                
                soTienPhaiTT = soLuongMua * giaXe;
                
                df = new DecimalFormat();
                txtSoTienPhaiTT.setText(df.format(soTienPhaiTT) + "");
                
            } else {
                grThanhToan.clearSelection();
            }
        }
    }//GEN-LAST:event_radTraGopActionPerformed

    private void radTraThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTraThangActionPerformed
        Object o = evt.getSource();
        if (o.equals(radTraThang)) {
            txtTraTruoc.setEnabled(false);
            cbxSoLanGop.setEnabled(false);
            
            txtTraTruoc.setText("");
            txtTienConLai.setText("");
            txtMoiLanGop.setText("");
            
            soLanTT = "0";
            
            if (txtSoLuongMua.getText().equals("") || cbxMaXe.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn xe và số lượng mua", "Cần chọn xe", JOptionPane.WARNING_MESSAGE);
                grThanhToan.clearSelection();
            } else if (validDataLapHopDong()) {
                String maXe = (String) cbxMaXe.getSelectedItem();
                int soLuongMua = Integer.parseInt(txtSoLuongMua.getText());
                double giaXe = Double.parseDouble(txtGiaXe.getText());
                if (soLuongMua <= 3) {
                    soTienPhaiTT = (soLuongMua * giaXe) * 0.98;
                    soTienDaTT = soTienPhaiTT;
                } else if (soLuongMua > 3) {
                    soTienPhaiTT = (soLuongMua * giaXe) * 0.95;
                    soTienDaTT = soTienPhaiTT;
                }
                df = new DecimalFormat();
                txtSoTienPhaiTT.setText(df.format(soTienPhaiTT) + "");
            } else {
                grThanhToan.clearSelection();
            }
        }
    }//GEN-LAST:event_radTraThangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLapHopDong;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JComboBox<String> cbxLoaiXe;
    private javax.swing.JComboBox<String> cbxMaKhachHang;
    private javax.swing.JComboBox<String> cbxMaXe;
    private javax.swing.JComboBox<String> cbxSoLanGop;
    private javax.swing.ButtonGroup grGioiTinh;
    private javax.swing.ButtonGroup grThanhToan;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDiaChiKH;
    private javax.swing.JLabel lblGiaXe;
    private javax.swing.JLabel lblGioiTinhKH;
    private javax.swing.JLabel lblHangXe;
    private javax.swing.JLabel lblHoTenKH;
    private javax.swing.JLabel lblLoaiXe;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblMaXe;
    private javax.swing.JLabel lblMauXe;
    private javax.swing.JLabel lblMoiLanGop;
    private javax.swing.JLabel lblNXS;
    private javax.swing.JLabel lblPhanKhoi;
    private javax.swing.JLabel lblSDTKH;
    private javax.swing.JLabel lblSoCCCD;
    private javax.swing.JLabel lblSoKhung;
    private javax.swing.JLabel lblSoLanGop;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblSoLuongMua;
    private javax.swing.JLabel lblSoTienPhaiTT;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTenXe;
    private javax.swing.JLabel lblThoiHanBH;
    private javax.swing.JLabel lblTienConLai;
    private javax.swing.JLabel lblTraTruoc;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JRadioButton radTraGop;
    private javax.swing.JRadioButton radTraThang;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtGiaXe;
    private javax.swing.JTextField txtHangXe;
    private javax.swing.JTextField txtHoTenKH;
    private javax.swing.JTextField txtMaHopDong;
    private javax.swing.JTextField txtMauXe;
    private javax.swing.JTextField txtMoiLanGop;
    private javax.swing.JTextField txtNSX;
    private javax.swing.JTextField txtPhanKhoi;
    private javax.swing.JTextField txtSDTKH;
    private javax.swing.JTextField txtSoCCCD;
    private javax.swing.JTextField txtSoKhung;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoLuongMua;
    private javax.swing.JTextField txtSoTienPhaiTT;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtThoiHanBH;
    private javax.swing.JTextField txtTienConLai;
    private javax.swing.JTextField txtTraTruoc;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }
    
    @Override
    public void mousePressed(MouseEvent e) {
        
    }
    
    @Override
    public void mouseReleased(MouseEvent e) {
        
    }
    
    @Override
    public void mouseEntered(MouseEvent e) {
        
    }
    
    @Override
    public void mouseExited(MouseEvent e) {
        
    }
    
    public String getDate(String lcDate) {
        return lcDate.substring(0, 10);
    }
    
    public void xoaTrangTTKhachHang() {
        txtHoTenKH.setText("");
        txtSDTKH.setText("");
        txtSoCCCD.setText("");
        txtDiaChiKH.setText("");
        radNam.setSelected(true);
    }
    
    public void nhapLai() {
        cbxMaKhachHang.setSelectedItem("");
        txtHoTenKH.setText("");
        txtSDTKH.setText("");
        txtSoCCCD.setText("");
        txtDiaChiKH.setText("");
        txtSoTienPhaiTT.setText("");
        txtTraTruoc.setText("");
        txtMoiLanGop.setText("");
        cbxMaXe.setSelectedItem("");
        txtTenXe.setText("");
        txtMauXe.setText("");
        txtNSX.setText("");
        txtHangXe.setText("");
        txtGiaXe.setText("");
        txtSoKhung.setText("");
        txtPhanKhoi.setText("");
        txtSoLuong.setText("");
        cbxLoaiXe.setSelectedItem("");
        txtMaHopDong.setText("");
        txtSoLuongMua.setText("");
        cbxSoLanGop.setEditable(false);
        txtMoiLanGop.setText("");
        txtTienConLai.setText("");
        grThanhToan.clearSelection();
        
        txtHoTenKH.requestFocus();
        
    }
    
    private void loadDataTuCSDLLenUI() throws SQLException {
        cbxSoLanGop.addItem("");
        cbxSoLanGop.addItem("2");
        cbxSoLanGop.addItem("3");
        khachHang_DAO = new KhachHangDAO();
        ArrayList<KhachHang> dsKH = khachHang_DAO.getAllKhachHang();
        cbxMaKhachHang.addItem("");
        for (KhachHang kh : dsKH) {
            cbxMaKhachHang.addItem(String.valueOf(kh.getMaKH()));
        }
        
        loaiSP_DAO = new LoaiSanPhamDAO();
        cbxLoaiXe.addItem("");
        ArrayList<LoaiXe> listLoaiXe = loaiSP_DAO.getAllLoaiSanPham();
        for (LoaiXe loaiXe : listLoaiXe) {
            cbxLoaiXe.addItem(loaiXe.getMaLoaiXe());
        }
        
        sanPham_DAO = new SanPhamDAO();
        cbxMaXe.addItem("");
        ArrayList<Xe> list = sanPham_DAO.getAllSanPham();
        for (Xe xe : list) {
            df = new DecimalFormat("###.##");
            cbxMaXe.addItem(xe.getMaXe());
        }
        
    }
    
    public void capNhatSoLuongXe() throws SQLException {
        
        String maXe = (String) cbxMaXe.getSelectedItem();
        String tenXe = txtTenXe.getText();
        String mauXe = txtMauXe.getText();
        String nuocSanXuat = txtNSX.getText();
        String hangXe = txtHangXe.getText();
        double giaBan = Double.parseDouble(txtGiaXe.getText());
        String loaiXe = cbxLoaiXe.getSelectedItem().toString();
        LoaiXe lXe = new LoaiXe(loaiXe);
        String soKhung = txtSoKhung.getText();
        String phanKhoi = txtPhanKhoi.getText();
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        int soLuongConLai;
        int soLuongMua = Integer.parseInt(txtSoLuongMua.getText());
        
        soLuongConLai = soLuong - soLuongMua;
        
        Xe xe = new Xe(maXe, tenXe, mauXe, nuocSanXuat, hangXe, giaBan, soKhung, phanKhoi, soLuongConLai, lXe);
        
        if (soLuongConLai == 0) {
            sanPham_DAO.deleteXe(maXe);
            
        } else if (soLuongConLai > 0) {
            sanPham_DAO.updateXe(xe);
        }
    }
//    Kiểm tra dữ liệu nhập vào khi tạo hợp đồng
    public boolean validDataLapHopDong() {
        CustomMessageDialog canhBaoNhapLieu = new CustomMessageDialog(gdDangNhap);
        String hoTenKH = txtHoTenKH.getText().trim();
        String soDT = txtSDTKH.getText().trim();
        String soCCCD = txtSoCCCD.getText().trim();
        String diaChi = txtDiaChiKH.getText().trim();
        
        String soLuongMua = txtSoLuongMua.getText();
        String soLuong = txtSoLuong.getText().trim();
        String maHopDog = txtMaHopDong.getText().trim();
        
        if (!(hoTenKH.length() > 0 && hoTenKH.matches("^[A-Z][a-z]+(\\s[A-Z][a-z]+)+$"))) {
            canhBaoNhapLieu.showMessage("Cảnh báo nhập liệu", "Họ tên khách hàng bắt đầu bằng chữ cái viết hoa, ít nhất 2 từ, không dấu.");
            txtHoTenKH.requestFocus();
            return false;
        }
        
        if (!(soDT.length() > 0 && soDT.matches("^(032|033|034|035|036|037|038|039|086|096|097|098|070|079|077|076|078|089|090|093|083|084|085|081|082|088|091|094|056|058|092|059|099)[0-9]{7}$"))) {
            canhBaoNhapLieu.showMessage("Cảnh báo nhập liệu", "Số điện thoại chưa hợp lệ, vui lòng kiểm tra lại đầu số, số điện thoại gồm 10 số, bắt đầu bằng số 0.");
            txtSDTKH.requestFocus();
            return false;
        }
        
        if (!(soCCCD.length() > 0 && soCCCD.matches("^0[0-9]{11}$"))) {
            canhBaoNhapLieu.showMessage("Cảnh báo nhập liệu", "Số căn cước công dân bao gồm 12 số, bắt đầu bằng số 0.");
            txtSoCCCD.requestFocus();
            return false;
        }
        if (!(diaChi.length() > 0 && diaChi.matches("[A-Za-z0-9 ]+"))) {
            canhBaoNhapLieu.showMessage("Cảnh báo nhập liệu", "Địa chỉ bắt đầu bằng chữ hoặc số, không chứa kí tự đặc biệt.");
            txtDiaChiKH.requestFocus();
            return false;
        }
        if (soLuongMua.length() > 0) {
            try {
                int slMua = Integer.parseInt(soLuongMua);
                int sl = Integer.parseInt(soLuong);
                if (slMua > sl) {
                    canhBaoNhapLieu.showMessage("Cảnh báo nhập liệu", "Số lượng xe hiện tại không đủ, vui lòng chọn ít hơn hoặc mua xe khác.");
                    txtSoLuongMua.requestFocus();
                    return false;
                }
            } catch (Exception e) {
                canhBaoNhapLieu.showMessage("Cảnh báo nhập liệu", "Số lượng xe mua phải là số dương.");
                txtSoLuongMua.requestFocus();
                return false;
            }
        }
        if (!(maHopDog.length() > 0 && maHopDog.matches("^HD[0-9]{6}"))) {
            canhBaoNhapLieu.showMessage("Cảnh báo nhập liệu", "Mã hợp đồng cú pháp: HD + 6 số.");
            txtMaHopDong.requestFocus();
            return false;
        }
        return true;
    }
    
}
